import Head from "next/head";
import styles from "../styles/Home.module.css";
import SignIn from "./SignIn";
import "bootstrap/dist/css/bootstrap.min.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chatly</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous"
        />
        <link rel="icon" href="/favicon.ico" />
        <div>
          <h1 className={styles.title}>Welcome to MERN Chat!</h1>

          <SignIn />

          <p className={styles.description}>
            A chat application that allows users to join a chat room something
            like slack. we can create chat rooms and share URLs.
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a target="_blank" rel="noopener noreferrer">
          By The hottest Dev Team
        </a>
      </footer>
    </div>
  );
}
